// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "8I343TFAh3g0gAswVtrXeZFpqTRh3P6X8Lgw4fIs65nWkwXcT4lf0ujIbWS8Jng9or5EIK";
}
}
}

